import { Github, FileVideo, Upload, Wand2 } from 'lucide-react';
import { Button } from "./components/ui/button";
import { Separator } from './components/ui/separator';
import { Textarea } from './components/ui/textarea';
import { Label } from './components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select';
import { Slider } from './components/ui/slider';

export function App() {

  return (
    <div className="min-h-screen flex flex-col">
      <div className="px-6 py-3 flex items-center justify-between border-b">
        <h1 className="text-xl font-bold">upload.ai</h1>

        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">
            Developed with ❤️{" "}
          </span>
          <Separator orientation="vertical" className="h-6" />
          <Button variant="outline" size="lg">
            <Github className="w-4 h-4 mr-2" />
            Github
          </Button>
        </div>
      </div>

      <main className="flex-1 p-6 flex gap-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="grid grid-rows-2  gap-4 flex-1 ">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Include the prompt for ia"
            />
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Result generated by AI"
            />
          </div>

          <p className="text-sm text-muted-foreground">
            Remember, do you need to use the{" "}
            <code className="text-violet-400">{"{transcription}"}</code>{" "}
            variable in order to add the selected video content
          </p>
        </div>
        <aside className="w-80 space-y-6">
          <form className="space-y-6">
            <label
              htmlFor="video"
              className={`
                border 
                w-full 
                flex
                flex-col
                items-center 
                justify-center 
                rounded-md 
                aspect-video 
                cursor-pointer
                border-dashed
                gap-2
                text-sm
                text-muted-foreground
                hover:border-violet-400
                hover:bg-primary/5
              `}
            >
              <FileVideo className="w-12 h-12" />
              Upload Video
            </label>
            <input
              type="file"
              id="video"
              accept="video/mp4"
              className="sr-only"
            />

            <Separator />

            <div className="space-y-1 flex flex-col gap-2">
              <Label htmlFor="trancription_prompt">Transcription prompt</Label>
              <Textarea
                id="trancription_prompt"
                className="h-20 leading-relaxed resize-none"
                placeholder="Include keywords mentioned in the video separated by commas (,)"
              />

              <Button type="submit" className="w-full">
                Upload video
                <Upload className="w-4  h-4 ml-2" />
              </Button>
            </div>
          </form>

          <Separator />

          <form className="space-y-6">
            <div className="space-y-2">
              <Label>Prompt</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select a prompt" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="title">Youtube title</SelectItem>
                  <SelectItem value="description">Youtube description</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Modelo</Label>
              <Select defaultValue="gpt3.5" disabled>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="gpt3.5">GPT 3.5 - Turbo 16k</SelectItem>
                </SelectContent>
              </Select>
              <span className="block text-xs text-muted-foreground italic">
                You will be able to customize this options soon.
              </span>
            </div>

            <Separator />

            <div className="space-y-4">
              <Label>Temperature</Label>
              <Slider min={0} max={1} step={0.1} />
              <span className="block text-xs text-muted-foreground italic leading-normal">
                Higher values tend to make the result more creative, but less
                accurate.
              </span>
            </div>

            <Separator />

            <Button type="submit" className="w-full">
              Execute
              <Wand2 className="w-4 h-4 ml-" />
            </Button>
          </form>
        </aside>
      </main>
    </div>
  );
}
